sudo: required

services:
  - docker

before_install: 'gem install bundler --pre;
  docker build -t suvvu/docker-practice -f frontend/Dockerfile.dev .'

script:
  - docker run -e CI=true suvvu/docker-practice npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1" # Dockerreact-env.eba-3c9s4ber.ap-south-1.elasticbeanstalk.com
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-ap-south-1-193016213103" #Search for s3 and check others
  bucket_path: "docker-react " #First time it will be app name
  on:
    branch: dev_branch
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
  edge: true
      