sudo: required

services:
  - docker

before_install:
  gem install bundler --pre
  docker build -t suvvu/docker-practice -f frontend/Dockerfile.dev .

script:
  - docker run -e CI=true suvvu/docker-practice npm run test -- --coverage